export const RESOURCE_NOINDEX_HEADER_NAME = 'X-Robots-Tag';
export const RESOURCE_NOINDEX_HEADER_VALUE = 'noindex';

export const RESOURCE_NOINDEX_HEADER = {
  key: RESOURCE_NOINDEX_HEADER_NAME,
  value: RESOURCE_NOINDEX_HEADER_VALUE,
} as const;

export const RESOURCE_NOINDEX_RESPONSE_HEADERS = {
  [RESOURCE_NOINDEX_HEADER_NAME]: RESOURCE_NOINDEX_HEADER_VALUE,
} as const;
